#!/bin/bash

set -euo pipefail
IFS=$'\n\t'
mkdir -p /NemBackup
cat <<EOF > /root/start
mv /root/NemBackup /
echo "Langs ENTER AJA"
mysql -u root -p < /NemBackup/database.sql
tar -xvpzf /NemBackup/panel.tar.gz -C /
tar -xvpzf /NemBackup/paymenter.tar.gz -C /
tar -xvzf /NemBackup/node.tar.gz -C /

EOF
chmod x+ /root/start
cp /var/www/pterodactyl/.env /NemBackup/pteroq.conf
cp /var/www/paymenter/.env /NemBackup/paymenter.conf
echo "LANGSUNG ENTER AJA INI"
mysqldump -u root -p --all-databases > /NemBackup/database.sql
tar -cvpzf /NemBackup/panel.tar.gz /etc/letsencrypt /var/www/pterodactyl /etc/nginx/sites-available/pterodactyl.conf /NemBackup/database.sql
tar -cvpzf /NemBackup/paymenter.tar.gz /etc/letsencrypt /var/www/paymenter /etc/nginx/sites-available/paymenter.conf /NemBackup/database.sql
tar -cvzf /NemBackup/node.tar.gz /var/lib/pterodactyl /etc/pterodactyl /etc/letsencrypt


clear
read -p "masukkan IP VPS tujuan: " target
ssh-keygen -R "$target" 2>/dev/null || true
scp -rp {/NemBackup,/root/start} root@$target:/root
